from snakemake.utils import min_version

min_version("6.4.0")

configfile: "config.yaml"

input_matrix="input/{sample}.hicqc.gz"
samples,= glob_wildcards(input_matrix)

input_line="input/{cell_line}_1.hicqc.gz"
cell_lines,= glob_wildcards(input_line)

include: "rules/1-partition.smk"
include: "rules/2-fulldata.smk"
include: "rules/3-data_to_hifive.smk"
include: "rules/4-importing.smk"
include: "rules/5-QuASAR.smk"
include: "rules/6-score.smk"
include: "rules/7-score_chr.smk"
include: "rules/8-QuASAR-Rep.smk"
include: "rules/9-combine_chr.smk"

rule all:
    input:
        expand(rules.score_chr.output, sample=samples),
        expand(rules.combine_chr.output, cell_line=cell_lines)
        